# Generated by Django 5.1.5 on 2025-01-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название документа')),
                ('description', models.TextField(blank=True, verbose_name='Описание документа')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Предмет')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Файл документа')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка на ресурс')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
        ),
    ]
