# Generated by Django 5.1.5 on 2025-01-28 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_agent', '0002_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='user',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
